### ISSUE TITLE
Elementare und Geistform

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#11]
Nach dem man Gestorben ist und zur Leiche rennt, verfolgen einen Feindlich gesinnte Elementare  und nach dem wiederbeleben greifen sie einen an. Die dazugehörigen Mobs die diese Elementare beschwören kommen ebenfalls hinzu.

**Comment by DarkBrain2580** [comment]
Kann ich bis jetzt nicht bestätigen.
