### ISSUE TITLE
Düstermarschen - Bezwingt Tethyr

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#12]
Die Quest in den Düstermarschen bei Theramore Bezwingt Tethyr : Tethyr  bleibt an einer stelle und die Mörser richten keinen Schaden an und haben keine Feueranimation, Tethyr ist nicht angreiffbar vom Spieler.
[https://de.wowhead.com/quest=27222/bezwingt-tethyr](url)

**Comment by DarkBrain2580** [comment]
Test nach Server Neustart.

**Comment by Ysanne313** [comment]
Laut Aussagen von Sacrificer, buggt der Tethyr immer noch rum und die kanonen gehen immer noch nicht

**Comment by DarkBrain2580** [comment]
Mies dafür fehlen einfach die scripts. Müssen vorrerst damit leben.
