### ISSUE TITLE
Wälder von Terokkar - der Große Knochenwurm

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#13]
Wälder von Terokkar, Scherbenwelt
Bei der Quest  Der Große Knochenwurm [https://de.wowhead.com/quest=10930/der-gro%C3%9Fe-knochenwurm](url)  despawnen die Kader der Alterschwachen Grollhufe [https://de.wowhead.com/npc=22105/altersschwacher-grollhuf](url) zu schnell für das Questitem das 5 sekunden zur aktivierung braucht.

**Comment by DarkBrain2580** [comment]
Test nach Server neustart.

**Comment by Ysanne313** [comment]
Order hats grad getestet,  trommel kann angewendet werden aber der qurm taucht nicht auf
