### ISSUE TITLE
NPC Rußtatze

### ISSUE THREAD

**Issue by Sanzo08** [elixyr-wow/Bugtracker#15]
Standort Loch Modan
https://datenbank.classic-wow.org/?npc=1225

Dieser NPC rennt mit einer erhöten geschwindigkeit auf seine Gegner zu.

**Comment by DarkBrain2580** [comment]
Nach Server Restart Testen wenn nicht geht rückmeldung geben.

**Comment by DarkBrain2580** [comment]
Nach dem keine Rückmeldung kommt denke ich das sich das problem erledigt hat.
