### ISSUE TITLE
Quest Reihe für den Schlüssel zur Sengenden Schlucht

### ISSUE THREAD

**Issue by Sanzo08** [elixyr-wow/Bugtracker#17]
Das Horn der Bestie
http://wowdata.buffed.de/quest/Sengende-Schlucht/Das-Horn-der-Bestie-3181
soweit alles ok 
Beschreibung
Bringt Margols gigantisches Horn zu Gebirgsjägerin Feinkiesel.
Wenn die Quest abgegebn wird is der Text auf Englisch.

Folgequests wie Besitznachweis und Endlich genau das gleiche.

Link. http://wowdata.buffed.de/quest/Loch-Modan/Besitznachweis-3182
Link. https://de.wowhead.com/quest=3201/endlich

Der schlüssel wird auch auf Englisch angezeigt.
hier der Link. https://datenbank.classic-wow.org/?item=5396

**Comment by DarkBrain2580** [comment]
Nach Server Neustart Testen.
