### ISSUE TITLE
Boreanische Tundra - Ritt auf dem magischen Teppich

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#20]
Bei der Quest in der Boreanischen Tundra  Ritt auf dem magischen Teppich [https://de.wowhead.com/quest=11636/ritt-auf-dem-magischen-teppich](url) wird man von Kel'Thuzad mit Gedankenschinden abgeschossen und stirbt an fallschaden und die quest kann dadurch nicht abgeschlossen werden

**Comment by DarkBrain2580** [comment]
Test nach Server neustart.

**Comment by Ysanne313** [comment]
jou so gehts definitiv, Khel'Thuzad haut nur einma drauf statt 2 mal , passt

**Comment by DarkBrain2580** [comment]
Ok dann mach ich zu das ding.
