### ISSUE TITLE
Todesritter - Rune des gefallenen Kreuzfahrers

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#22]
Die Rune des Todesritters Rune des gefallenen Kreuzfahrers [https://de.wowhead.com/spell=53344/rune-des-gefallenen-kreuzfahrers](url)  procct in einem 2 minuten kampf 3 ma,  hatte die proccrate etwas besser in erinnerung, kannste ma da nachschaun wie hoch die procs per minute sind ( ppm ) ?

**Comment by DarkBrain2580** [comment]
Laut wowhead kommentare ist es 2 mal.

**Comment by Ysanne313** [comment]
alles klar na dann schließ ich das hier.
