### ISSUE TITLE
Drachenöde - Die Rückkehr des Oberhäuptlings

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#23]
Bei der Quest Die Rückkehr des Oberhäuptlings [https://de.wowhead.com/quest=12069/die-r%C3%BCckkehr-des-oberh%C3%A4uptlings](url) bewegt sich [https://de.wowhead.com/npc=26608/unterk%C3%B6nig-anubetkan](url) nicht von der stelle und man kann ihn dadurch nicht töten, quest nicht abschließbar

**Comment by DarkBrain2580** [comment]
Wurde unten gespawnt nach Server neustart Testen ob man ih n Angreifen kann.

**Comment by DarkBrain2580** [comment]
Ist angreifbar und tropt was es soll.

**Comment by Ysanne313** [comment]
sauber
