### ISSUE TITLE
Drachenöde - Sarathstra, Geißel des Nordens

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#26]
Bei der Quest Sarathstra, Geißel des Nordens [https://de.wowhead.com/quest=12097/sarathstra-gei%C3%9Fel-des-nordens](url) soll man den NPC Rokhan [https://de.wowhead.com/npc=26859/rokhan](url) ansprechen das dieser den Drache  herbeiruft, es ist keine Gesprächsoption verfügbar

**Comment by DarkBrain2580** [comment]
Test nach Server Neustart.

**Comment by Ysanne313** [comment]
hmm der Rokhan hat noch keine Gesprächsoption und der Drache flattert kinderliederpfeifend   außerhalb der reichweite rum. villt würds reichen wenn er  etwas niedriger fliegen würde, das man den drachen angreifen könnte, aber bei der HP brauch ich ne grp um es genau zu testen. 200k HP +

**Comment by DarkBrain2580** [comment]
Drache ist neu gespawnt. Fehlerhaftes script.

**Comment by Ysanne313** [comment]
jio hab se am boden gesehn und umgehua, qs clear    auch  ne gute lösung :)
