### ISSUE TITLE
Grizzlyhügel - Neue Kraft für die Truppen

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#27]
Bei der Quest Neue Kraft für die Truppen [https://de.wowhead.com/quest=12070/neue-kraft-f%C3%BCr-die-truppen](url) muss man mit dem Item Splitter der Erde [https://de.wowhead.com/item=36764/splitter-der-erde](url) Grizzlyhügelriesen [https://de.wowhead.com/npc=26261/grizzlyh%C3%BCgelriese](url) verstärken. Nach der Anwendung wird der Questfortschritt nicht gewährt.

**Comment by DarkBrain2580** [comment]
Test nach Server Restart sollte aber gehen.

**Comment by Ysanne313** [comment]
sauber , funktioniert
