### ISSUE TITLE
Grizzlyhügel - Die angesengte Geißel

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#28]
Das Questitem Macks dunkler Grog [https://de.wowhead.com/item=35908/macks-dunkler-grog](url) bei der Quest Die angesengte Geißel [https://de.wowhead.com/quest=12029/die-angesengte-gei%C3%9Fel](url) hat eine zu hohe Abklingzeit . Derzeit 15 sekunden, laut wowhead 2 sekunden.

**Comment by DarkBrain2580** [comment]
Nach Server Restart sollte es gehen.
