### ISSUE TITLE
Drachenöde - Kein Ausweg

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#29]
Bei der Quest Kein Ausweg [https://de.wowhead.com/quest=12261/kein-ausweg](url) wird nachdem die Barriere vollständig aufgeladen wurde die Quest nicht abgeschlossen.

**Comment by DarkBrain2580** [comment]
Test nach Server Restart.

**Comment by Ysanne313** [comment]
sauber, geht
