### ISSUE TITLE
Drachenöde - Leichenfleddern

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#31]
Bei der Quest Leichenfleddern [https://de.wowhead.com/quest=11999/leichenfleddern](url)  droppen die Lootbaren Leichen  keine Pläne [https://de.wowhead.com/item=35783/pl%C3%A4ne-der-mondruhg%C3%A4rten](url). Die leichen verschwinden sofort nachdem man sie rechts angeklickt hat

**Comment by DarkBrain2580** [comment]
Test nach Server Restart.

**Comment by Ysanne313** [comment]
sanzo meinte um die 200 leichen für di epläne, bei mir gerade die erste,  vor dem eintrag im träcker um die 100 stück , bei order es selbe mit den gefühlten 100   wie haste die dropchance eingestellt ?

**Comment by DarkBrain2580** [comment]
Drop Chance lässt sich da leiter nicht einstellen dafür. So wie es nach dem nächsten Server Restart ist besser gehts nicht.
