### ISSUE TITLE
Zul Drak - Trollpatrouille: Standarten hoch

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#34]
Quest: Trollpatrouille: Standarten hoch [https://de.wowhead.com/quest=12502/trollpatrouille-standarten-hoch](url)  [ Tägliche Quest ]

Problem: Nach dem man an dem Drakkaripodest die Standarte [https://de.wowhead.com/item=38544/banner-des-argentumkreuzzugs](url) nutzt führt der Char eine Animation aus aber das banner wird nicht gestellt, somit kein Questfortschritt. Banner Nord ist die fehlerhafte , Ost und Süd funktionieren.

**Comment by Ysanne313** [comment]
-- Update --  mit dem char auf der Trepep gestanden wurde das Banner aufgestellt,  Nen Fix wäre angebracht weil etwas zu verwirrend

**Comment by DarkBrain2580** [comment]
Erledigt.
