### ISSUE TITLE
Zul Drak - Heb'jin erledigen

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#35]
Quest: Heb'Jin erledigen [https://de.wowhead.com/quest=12662/hebjin-erledigen](url)

Problem: Nach dem Betätigen der Trommel, Erscheint Heb'Jin [https://de.wowhead.com/npc=28636/hebjin](url) mit seiner Fledermaus. Nachdem er unten angekommen ist, despawnt Heb'jin und man kann ihn nicht mehr töten.

**Comment by DarkBrain2580** [comment]
Ist gespawnt nach Server neustart. Script felerhaft.
