### ISSUE TITLE
Zul Drak - Item drop

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#39]
In Zul Drak sollte das Item Untoter Halsreif [https://de.wowhead.com/item=38660/untoter-halsreif](url) von den folgenenden Mobs droppen

- Siechender Troll [https://de.wowhead.com/npc=28519/siechender-troll](url)

- Eitrige Monstrosität [https://de.wowhead.com/npc=28564/eitrige-monstrosit%C3%A4t](url)

- Eisberührter Erdwüter [https://de.wowhead.com/npc=29436/eisber%C3%BChrter-erdw%C3%BCter](url)

Nach gut 100 Siechender Troll droppte es immer noch nicht, kann man da ma schaun wie hoch die droprate ist ?

**Comment by DarkBrain2580** [comment]
Drop Chance etwas hochgestellt mal schauen sollte gehen jetzt.

**Comment by Ysanne313** [comment]
3 Mobs umgehau und da is er. sauber
