### ISSUE TITLE
Todesritter - Gargoyle

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#41]
Der Talentzauber des Unheilgi Todesritters Gargoyle beschwören https://de.wowhead.com/spell=49206/gargoyle-beschw%C3%B6ren verursacht   zu wenig schaden.  non-krit 100-140  und krit 210. sollte weitaus mehr sein

**Comment by DarkBrain2580** [comment]
Test Nach Server Restart.

**Comment by Ysanne313** [comment]
Unverändert
