### ISSUE TITLE
Schattenmondtal - Ich war schon vieles...

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#43]
Quest: Ich war schon vieles...  https://de.wowhead.com/quest=10514/ich-war-schon-vieles

Problem: Oronoks Eberpfeife https://de.wowhead.com/item=30462/oronoks-eberpfeife kan nnicht benutzt werden, es erscheint die meldung das man im falschen gebiet wäre

-- Order --

**Comment by DarkBrain2580** [comment]
Funktioniert ohne Probeleme an der den richtigen stellen.
