### ISSUE TITLE
Todesritter - Blutpräsenz

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#44]
Bei der Blutpräsenz https://db.rising-gods.de/?spell=48266  heilt man sich um 4 %  des verursachten Schadens. bei niedrigstufigen Gegner, graue mobs, ist dies nicht mehr der Fall

**Comment by DarkBrain2580** [comment]
Test nach Server Neustart.

**Comment by Ysanne313** [comment]
Also wenn der Server grad neugestartet wurde, dann gehts noch nit, grad zu grauen mobs um die lvl 55 und weder autohit noch zauber heilen mich um die 4 % des Schadens

**Comment by Ysanne313** [comment]
Nach Test heil ich mich immer noch nicht an niedrigeren gegner, gefühlt weniger als vorher. greif ein ziel an und slebst die zauber heilen nicht mit blutpräsenz
