### ISSUE TITLE
Heulender Fjord - Jetzt drehen wir mal richtig auf...

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#46]
Quest: Jetzt drehen wir mal richtig auf...  https://de.wowhead.com/quest=11421/jetzt-drehen-wir-mal-richtig-auf

Problem: Nachdem man an einer harpune steht un das Questitem Harpunensteuerungsmechanismus https://de.wowhead.com/item=34032/harpunensteuerungsmechanismus nutzt geschieht nichts.

**Comment by DarkBrain2580** [comment]
Test Nach Server Restart. Habe aber kein Gutes Gefühl.

**Comment by Ysanne313** [comment]
Sacrificer hatte vorhin geschrieben das die nit geht
