### ISSUE TITLE
Argentumtunier - Vor den  Toren des feindes

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#47]
Quest -  Vor den Toren des Feindes https://de.wowhead.com/quest=13857/vor-den-toren-des-feindes#english-comments

Problem:  Ein kleines aber zeitaufwendiges fehlerchen  bei der oben genanten quest ist, das wenn man dort auf das Angebundene Kampagnenschlachtross steigt und durch die Fußsoldaten der Knochenwache https://de.wowhead.com/npc=33438/fu%C3%9Fsoldat-der-knochenwache stürmt das diese nicht sterben,

PS keien ahnung wo ich die Id von dem anstürmen vom argentum tunierpferd da herbekomme

**Comment by DarkBrain2580** [comment]
bei mir gings.

**Comment by Ysanne313** [comment]
Negativ, die Fußsoldaten sterben nicht wenn ich auf ein anderes ziel anstürme und durch die fußsoldaten stürme. muss die einzeln umhaun, laut wowhead solltem die , wenn se beim anstürmen im weg sind, sterben

**Comment by DarkBrain2580** [comment]
Dann kann ich da momentan nichts dran ändern.
