### ISSUE TITLE
Arathihochland Quest Tod von unten

### ISSUE THREAD

**Issue by Ysanne313** [elixyr-wow/Bugtracker#9]
Tod von unten: Kanone besitzt keine Feueranimation und ist nich besetztbar, aktivierung  tötet aber gegnerische mobs.
[https://de.wowhead.com/quest=26628/tod-von-unten](url)

**Comment by DarkBrain2580** [comment]
Geht die Quest abzuschliesen oder nicht?

**Comment by Ysanne313** [comment]
ist abschließbar

**Comment by DarkBrain2580** [comment]
ok dann machen wir das einfach zu hier wenn man sie abschließen kann ist das rein ein optischer fehler. Der ist nicht so schlimm.
